export type SupportedArchiveFormat =
  | "zip"
  | "rar"
  | "7z"
  | "tar"
  | "tar-gz"
  | "tar-bz2"
  | "tar-xz"
  | "gz"
  | "bz2"
  | "xz"
  | "iso"
  | "cab"
  | "ar"
  | "cpio";

export interface ArchiveFormatMeta {
  id: SupportedArchiveFormat;
  name: string;
  description: string;
  acceptedExtensions: string[];
  heroTagline: string;
  formatSummary: string;
  exampleArchive: string;
  defaultValueProps?: string[];
  defaultWorkflow?: string[];
  defaultPitfalls?: string[];
  defaultUseCases?: string[];
}

export const archiveFormats: ArchiveFormatMeta[] = [
  {
    id: "zip",
    name: "ZIP",
    description:
      "ZIP is the most common archive format for Windows and cross-platform distribution. It supports compression, encryption, and multi-file bundling.",
    acceptedExtensions: [".zip", ".zipx"],
    heroTagline: "Preview and extract ZIP and ZIPX archives instantly in your browser",
    formatSummary:
      "Drop any ZIP or ZIPX archive to browse folders, copy specific files, or download everything without installing desktop tools.",
    exampleArchive: "brand-assets.zip",
    defaultValueProps: [
      "Instant previews for directories and individual files",
      "Handles encrypted archives with on-demand password prompts",
      "Download entire archive or selected files with one click",
      "Works offline once loaded—ideal for secure environments",
    ],
    defaultWorkflow: [
      "Drag a ZIP or ZIPX archive into the drop zone or use the file picker.",
      "Warm up the extraction engines for large or encrypted archives.",
      "Preview folders, select the files you need, and download them directly.",
    ],
    defaultPitfalls: [
      "Large archives can consume local memory—close other heavy tabs if needed.",
      "Password-protected archives require the exact password used during compression.",
      "Nested archives need to be downloaded and re-opened separately.",
    ],
    defaultUseCases: [
      "IT teams distributing application bundles",
      "Designers sending asset packs to clients",
      "Students downloading coursework archives",
      "Teams reviewing deliverables before importing to servers",
    ],
  },
  {
    id: "rar",
    name: "RAR",
    description:
      "RAR archives provide strong compression ratios and are common on Windows for sharing large datasets and software packages.",
    acceptedExtensions: [".rar"],
    heroTagline: "Open RAR v4 and v5 archives with password support—no desktop app required",
    formatSummary:
      "Inspect contents, unlock encrypted sections, and export individual files from any RAR archive completely in-browser.",
    exampleArchive: "project-backup.rar",
  },
  {
    id: "7z",
    name: "7-Zip",
    description:
      "7z archives use LZMA or LZMA2 compression to achieve excellent ratios for backups, firmware, and asset delivery.",
    acceptedExtensions: [".7z"],
    heroTagline: "Handle massive 7z archives with multi-threaded WebAssembly performance",
    formatSummary:
      "Preview multi-gigabyte archives locally, then download only the folders you need without re-uploading to another service.",
    exampleArchive: "datasets.7z",
  },
  {
    id: "tar",
    name: "TAR",
    description:
      "TAR archives are a Unix staple used to bundle files without compression. They often appear alongside gzip or bzip2 for packaging.",
    acceptedExtensions: [".tar"],
    heroTagline: "Explore TAR archives and extract just the directories you need",
    formatSummary:
      "Our extractor understands complex directory structures and lets you download subsets in seconds.",
    exampleArchive: "source.tar",
  },
  {
    id: "tar-gz",
    name: "TAR.GZ",
    description:
      "tar.gz (TGZ) combines TAR archiving with gzip compression. It is widely used for Linux packages, open-source releases, and backups.",
    acceptedExtensions: [".tar.gz", ".tgz"],
    heroTagline: "Unpack tar.gz releases right in the browser and grab only the files you need",
    formatSummary:
      "Drop tar.gz or tgz bundles, inspect versioned files, and download diffs without unpacking locally.",
    exampleArchive: "service-v2.1.0.tar.gz",
  },
  {
    id: "tar-bz2",
    name: "TAR.BZ2",
    description:
      "tar.bz2 archives use BZIP2 compression on top of TAR for stronger compression at the cost of slower decompression.",
    acceptedExtensions: [".tar.bz2", ".tbz2", ".tbz"],
    heroTagline: "Extract tar.bz2 archives generated by legacy build systems or mirrors",
    formatSummary:
      "Preview every folder, then export only the binaries or source files you really need—no command line required.",
    exampleArchive: "legacy-build.tbz2",
  },
  {
    id: "tar-xz",
    name: "TAR.XZ",
    description:
      "tar.xz archives leverage XZ compression for extremely small package sizes, common in modern Linux distributions.",
    acceptedExtensions: [".tar.xz", ".txz"],
    heroTagline: "Browse tar.xz packages used by Linux distros and firmware teams",
    formatSummary:
      "Works great for package maintainers reviewing release contents before shipping updates.",
    exampleArchive: "kernel-modules.txz",
  },
  {
    id: "gz",
    name: "GZIP",
    description:
      "GZIP compresses single files and is often used for logs, CSVs, and TAR archives (tar.gz).",
    acceptedExtensions: [".gz"],
    heroTagline: "Decompress .gz files instantly and inspect the output without CLI tooling",
    formatSummary:
      "Automatically infers the original filename so you can download the restored file right away.",
    exampleArchive: "metrics.csv.gz",
  },
  {
    id: "bz2",
    name: "BZIP2",
    description:
      "BZIP2 delivers higher compression ratios than gzip for single files and TAR bundles.",
    acceptedExtensions: [".bz2"],
    heroTagline: "Open .bz2 compressed data and repackage it without switching tools",
    formatSummary:
      "Useful when mirroring open-source releases or decomposing archives provided by older systems.",
    exampleArchive: "logs-2024-09-01.log.bz2",
  },
  {
    id: "xz",
    name: "XZ",
    description:
      "XZ compression is popular for package repositories, firmware, and resources that need maximum compression.",
    acceptedExtensions: [".xz"],
    heroTagline: "Handle huge .xz compressed files entirely in your browser",
    formatSummary:
      "Great for DevOps teams validating repository mirrors or unpacking firmware blobs.",
    exampleArchive: "rootfs.img.xz",
  },
  {
    id: "iso",
    name: "ISO",
    description:
      "ISO disk images replicate optical media and are common for operating system installers, firmware, and offline backups.",
    acceptedExtensions: [".iso"],
    heroTagline: "Mount ISO images virtually, browse their file systems, and extract select folders",
    formatSummary:
      "Inspect boot images, drivers, and assets without burning to physical media or mounting with admin rights.",
    exampleArchive: "ubuntu-24.04.iso",
  },
  {
    id: "cab",
    name: "CAB",
    description:
      "Microsoft Cabinet archives distribute drivers, installers, and system updates with optional compression and digital signatures.",
    acceptedExtensions: [".cab"],
    heroTagline: "Unpack CAB packages used by Windows installers and driver bundles",
    formatSummary:
      "Developers can verify contents before pushing updates to production devices.",
    exampleArchive: "driver-update.cab",
  },
  {
    id: "ar",
    name: "AR",
    description:
      "Unix AR archives bundle object files and are the container format for Debian (.deb) packages.",
    acceptedExtensions: [".ar", ".deb"],
    heroTagline: "Inspect .ar and .deb packages to review control files and payload archives",
    formatSummary:
      "Ideal for package maintainers auditing Debian packages without extracting everything locally.",
    exampleArchive: "sample-package.deb",
  },
  {
    id: "cpio",
    name: "CPIO",
    description:
      "CPIO archives power Linux initramfs images and build pipelines that need deterministic packaging.",
    acceptedExtensions: [".cpio", ".img"],
    heroTagline: "Open initramfs and CPIO archives used in embedded Linux",
    formatSummary:
      "Inspect boot images, modify configs, and export only what you need for debugging.",
    exampleArchive: "initramfs.cpio",
  },
];

export interface ArchiveModifierApplicability {
  onlyFormats?: SupportedArchiveFormat[];
  excludeFormats?: SupportedArchiveFormat[];
}

export interface ArchiveModifierContent {
  summary: string;
  valueProps: string[];
  workflowSteps: string[];
  pitfalls: string[];
  useCases: string[];
  faq: Array<{ question: string; answer: string }>;
  seoKeywords: string[];
  ctaTitle: string;
  ctaBody: string;
}

export interface ArchiveIntentModifier {
  slug: string;
  label: string;
  titleSuffix: string;
  heroTagline: string;
  metaDescription: string;
  applicability?: ArchiveModifierApplicability;
  content: ArchiveModifierContent;
}

export const archiveIntentModifiers: ArchiveIntentModifier[] = [
  {
    slug: "windows-it",
    label: "Windows IT Teams",
    titleSuffix: "for Windows IT Teams",
    heroTagline: "Audit installers, drivers, and update packages without breaking trusted workflows",
    metaDescription:
      "Extract ZIP, CAB, and RAR archives inside the browser to verify installers, driver bundles, and enterprise deployments without installing extra software.",
    applicability: {
      excludeFormats: ["cpio"],
    },
    content: {
      summary:
        "Keep deployment workflows fast by validating archives on locked-down machines. Everything runs client-side—perfect for air-gapped or admin-restricted environments.",
      valueProps: [
        "Preview installer contents before trusting unsigned packages",
        "Detect unexpected DLLs or scripts hidden inside driver bundles",
        "Share quick screenshots of archive trees with ticketing systems",
        "Works even on managed Windows accounts without PowerShell access",
      ],
      workflowSteps: [
        "Drop the archive from your deployment share into the extractor.",
        "Review the file tree for suspicious binaries or version mismatches.",
        "Download only the drivers or config files you need to patch.",
      ],
      pitfalls: [
        "Watch for nested archives—download and inspect them separately if needed.",
        "Unsigned CAB files may still contain malicious payloads—scan before distribution.",
        "Large archives require free disk space for temporary browser storage.",
      ],
      useCases: [
        "Validating OEM driver packages",
        "Auditing MSI installers delivered as ZIP/RAR",
        "Reviewing patch contents before software center deployment",
        "Sharing vendor-provided log bundles with security teams",
      ],
      faq: [
        {
          question: "Does this work on locked-down machines?",
          answer:
            "Yes. Everything executes in the browser sandbox, so no installation or admin rights are required—ideal for managed Windows fleets.",
        },
        {
          question: "Can I inspect CAB digital signatures?",
          answer:
            "We expose signature metadata in the archive details panel so you can verify publisher name and timestamp before deployment.",
        },
      ],
      seoKeywords: [
        "windows cab extractor",
        "inspect driver cab",
        "rar extractor windows",
        "zip viewer enterprise",
      ],
      ctaTitle: "Validate updates before they hit production",
      ctaBody:
        "Run installer archives through the browser first. Catch surprises before they ship to thousands of endpoints.",
    },
  },
  {
    slug: "linux-devops",
    label: "Linux DevOps",
    titleSuffix: "for Linux DevOps",
    heroTagline: "Check tarballs, initramfs images, and release artifacts right in your browser",
    metaDescription:
      "Inspect tar.gz, tar.xz, cpio, and other Linux-native archives locally to verify pipelines, releases, and container layers without leaving the browser.",
    content: {
      summary:
        "Debug CI artifacts, initramfs updates, and package releases without SSH-ing into build servers. Drop the archive, inspect the file tree, and export only the assets you need.",
      valueProps: [
        "Understands tar, tar.gz, tar.xz, cpio, and initramfs structures",
        "Keeps metadata intact so you can confirm permissions and owners",
        "Download manifests or systemd units for quick reviews",
        "Ideal for remote teams inspecting artifacts from tablets or Chromebooks",
      ],
      workflowSteps: [
        "Drag a tarball or initramfs image generated by CI.",
        "Expand critical directories (bin/, lib/, systemd/) to audit changes.",
        "Export the modified units or binaries for local testing.",
      ],
      pitfalls: [
        "Huge firmware images can exceed browser memory; trim them in CI if possible.",
        "Preserve symlinks by downloading the full archive when you need exact replicas.",
        "Encrypted archives still require the original passphrase.",
      ],
      useCases: [
        "Auditing release tarballs before tagging",
        "Inspecting initramfs changes from build pipelines",
        "Extracting only configuration files needed for a hotfix",
        "Comparing package payloads between nightly and stable builds",
      ],
      faq: [
        {
          question: "Can I view file permissions and owners?",
          answer:
            "Yes. Toggle the metadata view to see permissions, ownership, size, and timestamps exactly as stored in the archive.",
        },
        {
          question: "Does this support compressed cpio images?",
          answer:
            "Absolutely. We detect gzip, bzip2, and xz-compressed CPIO archives and unpack them seamlessly in the browser.",
        },
      ],
      seoKeywords: [
        "extract tar gz online",
        "inspect initramfs",
        "cpio extractor",
        "tar xz viewer",
      ],
      ctaTitle: "Ship releases with total confidence",
      ctaBody:
        "Spot configuration regressions before they hit production. Inspect artifacts in seconds, no server access required.",
    },
  },
  {
    slug: "firmware-analysis",
    label: "Firmware Analysts",
    titleSuffix: "for Firmware Analysts",
    heroTagline: "Peel apart firmware bundles and ROM images inside a secure browser sandbox",
    metaDescription:
      "Extract 7z, tar.xz, and other firmware archives locally to investigate payloads, scripts, and configuration files without flashing devices.",
    content: {
      summary:
        "Reverse-engineer firmware packages faster by previewing file trees, extracting config scripts, and grabbing assets for deeper analysis.",
      valueProps: [
        "Handles common firmware formats like 7z, tar.xz, and ISO",
        "Preview scripts and metadata before exporting",
        "Download only the sections you need for RE tools",
        "Sandboxes everything offline for sensitive investigations",
      ],
      workflowSteps: [
        "Load the firmware archive from your test bench or vendor portal.",
        "Inspect boot scripts, configs, or binary blobs inside the image.",
        "Export selected files for analysis in IDA, Ghidra, or Binwalk.",
      ],
      pitfalls: [
        "Some firmware images use custom formats; if detection fails, repackage with a supported tool first.",
        "Encrypted sections still require vendor keys or passphrases.",
        "Preserve offsets when necessary by downloading the entire archive for tooling like Binwalk.",
      ],
      useCases: [
        "Analyzing router or IoT firmware drops",
        "Extracting configuration defaults for comparison",
        "Investigating suspected malware inside appliance updates",
        "Preparing partial updates for lab flashing",
      ],
      faq: [
        {
          question: "Will this modify the firmware image?",
          answer:
            "No. We only read archive contents. Use the download buttons to export files—the original image stays untouched.",
        },
        {
          question: "Can I preview scripts or plain-text configs?",
          answer:
            "Yes. Select a file to view its metadata and quick content preview before deciding to download it.",
        },
      ],
      seoKeywords: [
        "extract firmware 7z",
        "tar xz firmware",
        "iso firmware viewer",
        "iot firmware analysis",
      ],
      ctaTitle: "Accelerate firmware tear-downs",
      ctaBody:
        "Investigate vendor updates without flashing devices. Extract, inspect, and share findings faster than ever.",
    },
  },
  {
    slug: "education",
    label: "Education",
    titleSuffix: "for Students & Educators",
    heroTagline: "Open class archives from Chromebooks or managed devices with zero installs",
    metaDescription:
      "Extract ZIP, TAR, and 7z coursework archives on any device—ideal for classrooms, Chromebooks, and remote learning setups.",
    content: {
      summary:
        "Make it easy for students to unpack project templates and submit work without admin rights. Everything runs in the browser for true device agnosticism.",
      valueProps: [
        "Supports the most common assignment formats (ZIP, TAR, 7z)",
        "No installation required—works on Chromebooks and tablets",
        "Preview files before downloading to confirm you grabbed the right folder",
        "Accessible UI with keyboard shortcuts and dark mode",
      ],
      workflowSteps: [
        "Drag the assignment archive into the page or tap to browse.",
        "Preview project folders to find the starter code or PDF handout.",
        "Download only the files you need or export the entire folder structure.",
      ],
      pitfalls: [
        "Large media archives may be slow on low-memory devices—download in smaller batches if possible.",
        "Password-protected archives still need the passphrase from your instructor.",
        "Maintaining folder structure is important when re-submitting—download entire directories if unsure.",
      ],
      useCases: [
        "Students unpacking starter code archives",
        "Teachers distributing lab resources",
        "Peer review of group submissions",
        "Workshops sharing sample datasets",
      ],
      faq: [
        {
          question: "Does this work offline?",
          answer:
            "Yes. Once the page loads, extraction happens entirely offline—perfect for classrooms with limited connectivity.",
        },
        {
          question: "Can I use this on a Chromebook?",
          answer:
            "Absolutely. The extractor is optimized for ChromeOS and touch devices with full keyboard navigation.",
        },
      ],
      seoKeywords: [
        "unzip chromebook",
        "extract tar online",
        "7z viewer chrome",
        "school zip extractor",
      ],
      ctaTitle: "Get to the assignment faster",
      ctaBody:
        "Skip the IT requests. Unpack course materials instantly and focus on learning.",
    },
  },
];

export function isArchiveModifierApplicable(
  modifier: ArchiveIntentModifier,
  format: SupportedArchiveFormat,
): boolean {
  const { applicability } = modifier;
  if (!applicability) return true;
  if (applicability.onlyFormats && !applicability.onlyFormats.includes(format)) {
    return false;
  }
  if (applicability.excludeFormats && applicability.excludeFormats.includes(format)) {
    return false;
  }
  return true;
}
